### ISSUE TITLE
Continue to show the "browse feeds" option

### ISSUE THREAD

**Issue by frecar** [mocco/feedhuddler#74]
I liked this feature: https://feedhuddler.com/feeds/

But it is only linked to when I don't subscribe to any feeds, maybe you can still link to it even though I have started to subscribe on some feeds?

**Comment by relekang** [comment]
Good idea! Thanks for the feedback :sparkles: 

I think a navbar is due to make navigation on the site easier.

**Comment by relekang** [comment]
@frecar What do you think of how it is now?
